package dev.ujhhgtg.wekit.utils

import java.lang.reflect.Modifier

@Suppress("UNCHECKED_CAST", "NOTHING_TO_INLINE")
inline fun <T> Any.cast(): T = this as T

fun describeContent(obj: Any?): String {
    if (obj == null) return "Object is null"

    val jClass = obj.javaClass
    val sb = StringBuilder()

    // 1. Class Name
    sb.appendLine("Class: ${jClass.canonicalName ?: jClass.name}")

    // 2. Hierarchy (Superclass and Interfaces)
    val superclass = jClass.superclass
    val interfaces = jClass.interfaces
    if (superclass != null && superclass != Any::class.java) {
        sb.appendLine("Extends: ${superclass.simpleName}")
    }
    if (interfaces.isNotEmpty()) {
        sb.appendLine("Implements: ${interfaces.joinToString { it.simpleName }}")
    }

    // 3. Fields
    sb.appendLine("--- Fields ---")
    // .declaredFields gets fields in this class; use .fields for public inherited fields
    jClass.fields.forEach { field ->
        try {
            field.isAccessible = true // Access private fields
            val value = field.get(obj)
            val type = field.type.simpleName

            val displayValue = when {
                value == null -> "null"
                isSimpleType(value) -> value.toString()
                else -> "Complex Object (Identity: ${System.identityHashCode(value)})"
            }

            sb.appendLine("${field.name}: $type = $displayValue")
        } catch (e: Exception) {
            sb.appendLine("${field.name}: [Inaccessible]")
        }
    }

    // 4. Methods
    sb.appendLine("--- Methods ---")
    jClass.methods.forEach { method ->
        // Filter out synthetic methods (like those generated by the compiler)
        if (!method.isSynthetic) {
            val params = method.parameterTypes.joinToString { it.simpleName }
            val returnType = method.returnType.simpleName
            val modifiers = Modifier.toString(method.modifiers)

            sb.appendLine("$modifiers $returnType ${method.name}($params)")
        }
    }

    return sb.toString()
}

fun isSimpleType(value: Any): Boolean {
    val jClass = value.javaClass
    return jClass.isPrimitive ||
            value is Number ||
            value is String ||
            value is Boolean ||
            value is Char ||
            // Check if the class has overridden toString() specifically
            try {
                @Suppress("PLATFORM_CLASS_MAPPED_TO_KOTLIN")
                jClass.getMethod("toString").declaringClass != Object::class.java
            } catch (e: Exception) {
                false
            }
}
